[versions]
kotlin-version = "2.0.0"

[libraries]
junit5 = { module = "org.junit.jupiter:junit-jupiter", version = "5.10.2" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin-version" }

[bundles]
junit = ["junit5", "kotlin-test-junit5"]

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
