name: "Home Former"
version: "0.3.1"
slug: "homeformer"
description: >-
  Former of homes
arch:
  - amd64
  - aarch64
url: "https://github.com/DonRobo/home-former"
ports:
  8080/tcp: null
image: ghcr.io/donrobo/home-former
startup: application
ingress: true
ingress_port: 8080