name: Kotlin CI with Gradle

on:
  push:
    #    branches:
    #      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        env:
          GH_USER: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish distribution
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew publish
        env:
          GH_USER: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REF: ${{ github.ref }}

      - name: Publish container images
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew jib
        env:
          GH_USER: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

